# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 60, 601, 451))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 250, 31, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PgUp = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PgUp.setObjectName("PgUp")
        self.verticalLayout.addWidget(self.PgUp)
        self.PgDown = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PgDown.setObjectName("PgDown")
        self.verticalLayout.addWidget(self.PgDown)
        self.map_choose = QtWidgets.QComboBox(self.centralwidget)
        self.map_choose.setGeometry(QtCore.QRect(10, 10, 161, 22))
        self.map_choose.setObjectName("map_choose")
        self.map_choose.addItem("")
        self.map_choose.addItem("")
        self.map_choose.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 10, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.search_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.search_text.setObjectName("search_text")
        self.horizontalLayout.addWidget(self.search_text)
        self.search_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.reset_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YandexMap"))
        self.PgUp.setText(_translate("MainWindow", "+"))
        self.PgDown.setText(_translate("MainWindow", "-"))
        self.map_choose.setItemText(0, _translate("MainWindow", "Схема"))
        self.map_choose.setItemText(1, _translate("MainWindow", "Спутник"))
        self.map_choose.setItemText(2, _translate("MainWindow", "Гибрид"))
        self.label_2.setText(_translate("MainWindow", "Поиск:"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
        self.reset_btn.setText(_translate("MainWindow", "Сброс"))
